### ISSUE TITLE
How do you install the prereq's? 

### ISSUE THREAD

**Issue by juggledad** [blechdom/node-red-contrib-ffprobe#1]
Could you give some guidence on instaling the ffprobe and ffprobe-static. In searching, it looks like they are part of ffmpeg(??) so I tried doing a 

`sudo apt install ffmpeg` then `npm install node-red-contrib-ffprobe`

and both installs look good, but after starting node-red the node is not found in the sidebar and using the pallette manager it shows

```
node-red-contrib-ffprobe
1.0.2
Error: Cannot find module 'ffprobe' (line:4)

```

Is that the way to install the modules and Is something needed in the settings.js and if so what?

Thanks in advance.

**Comment by juggledad** [comment]
Well I thought I had the solution, I used
```
cd .node-red
npm install ffprobe
npm install ffprobe-static
```
and restarted NR and the node showed up (Yea!)
tried the flow in the flow library and changed the path to an existing file on my rpi, hit deploy and pressed the inject button and BOOM node-red crashes
```
22 Nov 14:58:46 - [info] Started modified flows
ffprobe path: /home/pi/walks.mp4
22 Nov 14:58:51 - [red] Uncaught Exception:
22 Nov 14:58:51 - Error: spawn /home/pi/.node-red/node_modules/ffprobe-static/bin/linux/arm/ffprobe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```
any thoughts?

**Comment by kamii1000** [comment]
I'm having the same issue as you have mentioned.
Did you find any solution? Can you please share?

Thanks

**Comment by juggledad** [comment]
Nope, never got it working and no response from the author
